on:
  push:
    branches: ["Taranjot/**", "Minh/**", "jeremiah/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 'node'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Run frontend tests
        working-directory: frontend
        run: npm test -- --watchAll=false

      - name: Run backend tests
        working-directory: backend
        run: npm test -- --watchAll=false

  create-pull-request:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create Pull Request
        run: gh pr create -B main -H ${{ github.ref_name }} --title "Merge ${{ github.ref_name }} into main" --body "Automatic PR from Github Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: github.com/qwertyqwerty223/ACIT-2911-Project-Term-Application
